const formatAnalyzedAt = (timestamp) => {
  if (!timestamp) return null;

  const parsed = new Date(timestamp);
  if (Number.isNaN(parsed.getTime())) return null;

  return parsed.toLocaleTimeString([], {
    hour: '2-digit',
    minute: '2-digit'
  });
};

const HeaderCard = ({ username, metadata }) => {
  if (!username) return null;

  const analyzedAt = formatAnalyzedAt(metadata?.timestamp);
  const isCached = Boolean(metadata?.cached || metadata?.cacheHeader === 'HIT');

  return (
    <div className="mb-6">
      <p className="text-xs font-semibold uppercase tracking-widest" style={{ color: 'var(--color-accent)' }}>
        Developer Profile
      </p>
      <h1 className="mt-1.5 text-3xl font-bold tracking-tight text-primary">@{username}</h1>
      <p className="mt-1 text-sm text-muted">Analytics generated by DevTrack — scores, trends, and role fit.</p>

      <div className="mt-3 flex flex-wrap items-center gap-2">
        <span
          className="rounded-full border px-2.5 py-1 text-xs font-medium"
          style={{
            borderColor: isCached ? '#bfdbfe' : '#a7f3d0',
            backgroundColor: isCached ? '#eff6ff' : '#f0fdf9',
            color: isCached ? '#1d4ed8' : '#065f46'
          }}
        >
          {isCached ? 'Cached result' : 'GitHub API live'}
        </span>

        {analyzedAt && (
          <span
            className="rounded-full border px-2.5 py-1 text-xs font-medium"
            style={{ borderColor: 'var(--color-line)', backgroundColor: 'var(--color-surface)', color: 'var(--color-muted)' }}
          >
            analyzed at {analyzedAt}
          </span>
        )}
      </div>
    </div>
  );
};

export default HeaderCard;
