const HeaderCard = ({ username }) => {
  if (!username) return null;

  return (
    <div className="mb-6">
      <p className="text-xs font-semibold uppercase tracking-widest" style={{ color: 'var(--color-accent)' }}>
        Developer Profile
      </p>
      <h1 className="mt-1.5 text-3xl font-bold tracking-tight text-primary">@{username}</h1>
      <p className="mt-1 text-sm text-muted">Analytics generated by DevTrack — scores, trends, and role fit.</p>
    </div>
  );
};

export default HeaderCard;
